name: 'Momento OSS README generator'
description: 'Processes a README template for a Momento SDK, inserts standardized header etc., and commits'
author: 'Momento'
inputs:
  project_type:
    required: true
    description: 'sdk or other'
  sdk_language:
    required: false
    description: 'JavaScript, Python, etc.'
  dev_docs_slug:
    required: false
    description: 'The slug in the dev docs SDKs section that we should link to, e.g. "nodejs" or "python"'
  multiple_sdks:
    required: false
    description: 'Set to true if this SDK README describes more than one SDK'
  omit_html_head:
    required: false
    description: 'If true, omit the SEO html head element to avoid rendering issues in package repos such as pypi'
  project_status:
    required: true
    description: 'official or incubating'
  project_stability:
    required: true
    description: 'experimental, alpha, beta, or stable'
  template_file:
    required: false
    description: 'path to readme template file'
    default: 'non-sdk.template.md'
  output_file:
    required: false
    description: 'output file path to write generated README'
    default: 'README.md'
runs:
  using: 'composite'
  steps:
    - uses: momentohq/standards-and-practices/github-actions/oss-readme-template@gh-actions-v1
      with:
        project_type: "${{ inputs.project_type }}"
        sdk_language: "${{ inputs.sdk_language }}"
        project_status: "${{  inputs.project_status }}"
        project_stability: "${{ inputs.project_stability }}"
        template_file: "${{ inputs.template_file }}"
        output_file: "${{ inputs.output_file }}"
        usage_example_path: "${{ inputs.usage_example_path }}"

    - shell: bash
      run: |
        git status
        cat README.md
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Update templated README.md file

        # Optional glob pattern of files which should be added to the commit
        # Defaults to all (.)
        # See the `pathspec`-documentation for git
        # - https://git-scm.com/docs/git-add#Documentation/git-add.txt-ltpathspecgt82308203
        # - https://git-scm.com/docs/gitglossary#Documentation/gitglossary.txt-aiddefpathspecapathspec
        file_pattern: "${{ inputs.output_file }}"

        # Optional commit user and author settings
        commit_user_name: Momento GitHub Actions Bot
        commit_user_email: github-actions-bot@momenthohq.com
