name: 'Momento SDK README generator'
description: 'Processes a README template for a Momento SDK, inserts standardized header etc.'
author: 'Momento'
inputs:
  project_type:
    required: true
    description: 'sdk or other'
  sdk_language:
    required: false
    description: 'JavaScript, Python, etc.'
  project_status:
    required: true
    description: 'official or incubating'
  project_stability:
    required: true
    description: 'alpha, beta, stable'
  template_file:
    required: false
    description: 'path to readme template file'
    default: 'README.template.md'
  output_file:
    required: false
    description: 'output file path to write generated README'
    default: 'README.md'
  usage_example_path:
    required: false
    description: 'path to usage example file'
runs:
  using: 'node16'
  main: 'dist/index.js'
