name: 'Momento SDK README generator'
description: 'Processes a README template for a Momento SDK, inserts standardized header etc.'
author: 'Momento'
inputs:
  project_type:
    required: true
    description: 'sdk or other'
  sdk_language:
    required: false
    description: 'JavaScript, Python, etc.'
  dev_docs_slug:
    required: false
    description: 'The slug in the dev docs SDKs section that we should link to, e.g. "nodejs" or "python"'
  multiple_sdks:
    required: false
    description: 'Set to true if this SDK README describes more than one SDK'
  omit_html_head:
    required: false
    description: 'If true, omit the SEO html head element to avoid rendering issues in package repos such as pypi'
  project_status:
    required: true
    description: 'official or incubating'
  project_stability:
    required: true
    description: 'alpha, beta, stable'
  template_file:
    required: false
    description: 'path to readme template file'
    default: 'README.template.md'
  output_file:
    required: false
    description: 'output file path to write generated README'
    default: 'README.md'
runs:
  using: 'node16'
  main: 'dist/index.js'
